### PR TITLE
Adding SemVer support

### PR DESCRIPTION
**Pull request by kenjiuno**
This pr will add SemVer support.
Not tested well so far.

### CODE REVIEW

**Comment by Deadpikle** [comment]
@kenjiuno Any update? Will you be working on this any more?

**Comment by kenjiuno** [comment]
Currently no update from me about this pr.

If there are any points to be fixed, I can work on it.

**Comment by DanieleVar** [comment]
@Deadpikle do you think that this PR will be accepted? 
I'm managing two channels for beta and stable updates but I would like to have the suffix "-beta" on my installer :)
Thanks

**Comment by Deadpikle** [comment]
@DanieleSky yes but I may modify things a little bit. At a cursory glance there are now two filter systems and there probably should only be one. Sorry this project hadn't been a huge priority lately. Will see what I can do to integrate what is here by early next week. Keep in mind the app cast generator may or may not have compatibility depending on if I have time to add that in too (unless someone else adds a PR for that).

**Comment by DanieleVar** [comment]
Thank you @Deadpikle 
About the generator is not a problem because I'm using the ``--file-version `` option to force the version in appcast.xml.
I'll try to watch into the generator to make the modify and the PR ;)

**Comment by Deadpikle** [comment]
Merged with some changes to remove the duplicate filtering process and fix a few typos/add some more tests/that sort of thing. My changes aren't necessarily perfect (namely there is a duplicate `delegate` and `IAppCastFilter` definition; may change how things work in larger restructuring later on) but it's now available and rolling out to NuGet preview.

Need to get this into the README somewhere for better docs.

**Comment by Deadpikle** [comment]
And RE: The app cast generator — I'm not sure that any changes here are necessary, actually. :-)

**Comment by Deadpikle** [comment]
And a final thank you to @kenjiuno for implementing this — really appreciate it! ^_^ Sorry it took so long.

**Comment by DanieleVar** [comment]
Hi @Deadpikle 
when do you think to make the new release with this PR?
I would like to test

**Comment by Deadpikle** [comment]
> Hi @Deadpikle when do you think to make the new release with this PR? I would like to test

This is already available in preview build `3.0.0-preview20240120001` and is not planned to be backported due to the breaking changes it contained.

**Pull request merged**
