### PR TITLE
WIP: Support for Info.plist

### PR DESCRIPTION
**Pull request by mphill**

### CODE REVIEW

**Comment by mphill** [comment]
@Deadpikle I need some guidance on how to handle the Company Name and constructor.  This PR should allow me to start testing MacOS updates with Xamarin.

Thanks!

**Comment by Deadpikle** [comment]
For company name, you can either leave it blank, or we can document a special string that users can use to access it. `NSUCompanyName` or something (NSU = Net Sparkle Updater).

For the constructor, some refactoring needs to happen, which I need to find some time for here in the next few days. Thanks for your patience (and for another contribution)!

**Comment by Deadpikle** [comment]
@mphill Sorry for the wait. I just pushed a change to the `develop` branch that makes `Configuration` objects take an `IAssemblyAccessor`, which makes them much more configurable. You should be able to refactor things now -- an `IAssemblyAccessor` class that grabs data from `Info.plist` and a `Configuration` subclass that saves/loads to `NSUserDefaults`. Then users will be able to mix and match things for their use case, e.g. `new SparkleUpdater(...) { new NSUserDefaultsConfiguration(new InfoPlistAccessor()) }` or similar. This way, users can save and load to JSON if they want instead of NSUserDefaults.

As far as the company name for `Info.plist`: for now, returning `CFBundleIdentifier` if available makes the most sense to me.

Please ping me again when you've got things working and I'll try to be a little more on top of this PR. :)

**Comment by Deadpikle** [comment]
@mphill  Any update?

**Comment by Deadpikle** [comment]
Closing due to lack of author response and not-needed-at-this-point Xamarin project.

**Pull request closed without merging**
