### PR TITLE
--overwrite-old-items flag is failing because of equality comparison on semVerLikeVersion and instead duplicates are left in the feed

### PR DESCRIPTION
**Pull request by robbiehinch**

### CODE REVIEW

**Comment by Deadpikle** [comment]
@robbiehinch Thank you very much for filing a bug AND a PR to fix it AND a unit test to make sure it stays fixed! Appreciate it very much!

I did go ahead and expand the test just a little bit to make sure that it works if `OverwriteOldItemsInAppcast` is `false` and to use semantic versioning.

Again, thank you!! :-)

**Comment by robbiehinch** [comment]
@Deadpikle thank you for continuing to maintain this project which has been very useful for my team. We're using it in a github build action at the moment, by installing it like this:

`dotnet tool install --global NetSparkleUpdater.Tools.AppCastGenerator`

Can you help me to understand when this change would make it into the package that is getting retrieved using `dotnet tool install`, please?

**Comment by Deadpikle** [comment]
Should already be available. It was deployed yesterday. :)

**Comment by Deadpikle** [comment]
You can see on the NuGet feed here: https://www.nuget.org/packages/NetSparkleUpdater.Tools.AppCastGenerator/2.8.3

You're looking for v2.8.3.

Glad to know it's been helpful!

**Pull request merged**
