### PR TITLE
Add option to not overwrite app cast to app cast generator -- #167

### LINKED ISSUE #167: App cast generator: Add option to re-parse existing app cast and add (only?) new items rather than recreate entire app cast
This would allow you to use CI/CD more easily by retaining your full history without having to get the signatures again for old binaries.

Probably would need to add a new flag to the app cast generator to this that defaulted to `false`.

### PR DESCRIPTION
**Pull request by Deadpikle**
Add an option to the app cast generator such that users can choose not to overwrite the existing app cast file and thus retain full app cast history without having all the binaries sitting around. Useful in CI/CD setups and if you don't want binaries to hog up your disk.

TODO:

* [x] Test the code with your own stuff (sanity checks)
* [x] Do anything to make sure conflicting options not used at the same time if there are any conflicting options (result: not sure that there are any conflicting options! :) )
* [x] Add another option to allow for overriding the version in the existing app cast if a binary is found (in other words, always use the binaries found but keep old stuff)
* [x] Write some unit tests (see #273)
* [x] Deploy new live version (new version # and all that)

If anyone sees this and is bored/has time and wants to help, feel free. It might be a while before I get back here.

Closes #167

### CODE REVIEW

**Comment by Deadpikle** [comment]
(this comment is now old, see initial PR notes) TODO:

* [x] Test the code with your own stuff (sanity checks)
* [x] Do anything to make sure conflicting options not used at the same time if there are any conflicting options (result: not sure that there are any conflicting options! :) )
* [x] Add another option to allow for overriding the version in the existing app cast if a binary is found (in other words, always use the binaries found but keep old stuff)
* [ ] Write some unit tests
* [ ] Deploy new live version (new version # and all that)

If anyone sees this and is bored/has time and wants to help, feel free. It might be a while before I get back here.

**Comment by johncclayton** [comment]
I just threw a PR targeting #270 - but haven't done anything other than the basic manual testing to prove it works.

**Comment by johncclayton** [comment]
Don't merge this yet... I just found a bug, after adding a new binary - I compared the files... this is what I see... eeek. so I\'ll take a look at how I re-introduce the right app name.

image

**Comment by johncclayton** [comment]
Ok, I think the following would make sense - feedback would be great.  I think the "product name" option is superfluous with the reparse option.  The code should simply pull the <title> tag from the existing XML and not rely on the user to provide -n "product name" that happens to be the same.  With a re-parse the intent is anyway to add to an existing .xml file - so as long as the XML file has one existing item, or better said an existing production name - we just take that. 

Work for you?

**Comment by Deadpikle** [comment]
Hey, thanks for your work!! Really appreciate that. I agree with your assessment.

I made a few changes. Notable:

* Renamed `--re-parse-existing` to `--reparse-existing`. 
* Added `--overwrite-old-items`
* Various cleanup items for safety and stuff, such as making sure the existing <title> wasn't empty.

I did some sanity checks on my own. Seems to work OK. However, I'm working on getting things at least someone unit-testable at the moment. See #273. I don't plan on changing anything feature wise unless stuff comes up in unit tests at this point. I don't know how deep I'll get into unit testing before rolling out a new version.

{Note: Right now, I only have time to work on this because another project is waiting on some answers from someone else. Once I get those, I'll be swamped again. 😅 Really, appreciate you taking a look and testing this!)

**Comment by Deadpikle** [comment]
@johncclayton Could you give this a smoke test and make sure it works? If so, I think it's ready to merge. I refactored things and added some unit tests (which did reveal some bugs!).

More unit testing could always be done to test out all the different options for the app cast generator at this point, but it's in a **much** better place than it used to be with a class that is actually somewhat testable!

EDIT: Argh how are unit tests working locally and not on CI?! ....well once those are fixed it should be good...it lights up all green on my Windows machine but somehow the tests are failing on Ubuntu....argh...

**Comment by johncclayton** [comment]
I re-forked the entire repo and ran the unit tests.  I'm stumped on a problem I'm encountering.  When I run ALL the tests at once, CanCreateSimpleAppCast fails.  If I run that single test again, it works - this is 100% repeatable. 

At first I figured; ah - the unit tests are running in parallel - so would it be a conflict between CanCreateSimpleAppCast and CanFindBinaries.  I changed the code in GetCleanTempDir to use absolutely unique names based on the caller method attribute - the tests still fail because the calculated signatures don't match. 

Check below - the new var sigFromFile is holding a different signature compared with items[0].DownloadSignature.

image

I started debugging and the UTF8 bytes read in by the signature manager do in fact seem to be the same.  This is when I started writing this message - any clues as to what is going on and where I might look next?

**Comment by Deadpikle** [comment]
The tests are a little better now, but not 100%. See https://github.com/NetSparkleUpdater/NetSparkle/pull/270/commits/e150532e428b66f52410c8247210a27868f67b24. 

Basically, things aren't being cleaned up properly, and I'm pretty sure that's where the problem lies. Test setup/teardown needs to be looked at for each test. Any temp keys created for a test need to be wiped by the end of the test, including environment vars.

As far as the signature not matching: That's expected, actually. Signatures on the same binary can look slightly different each time you run them. (I know this from experience, not from the underlying math, unfortunately, so I'm not sure what the reason for that is. It's not like a SHA-256 hash or something where it's the same every time. ...I think? I could confirm this with the original Sparkle repo if needed.)

**Comment by johncclayton** [comment]
Huh?  Signatures not matching sounds ... how shall I put this: really not right at all.  I am actually wondering if the keys are being re-generated during a parallel run; that would account for this behaviour.

I'll try to prove this later on today before going further.

**Comment by johncclayton** [comment]
I have changed the signature tests (and appcast maker test) to make use of an ICollectionFixture that exposes a single signature manager - this seems to do the trick.

**Comment by Deadpikle** [comment]
> Huh? Signatures not matching sounds ... how shall I put this: really not right at all. I am actually wondering if the keys are being re-generated during a parallel run; that would account for this behaviour.
> 
> I'll try to prove this later on today before going further.

So I was only half crazy here. See [this doc on ed25519 signatures](https://github.com/RubyCrypto/ed25519/blob/main/README.md). Here's the applicable part:

> Deterministic: Unlike (EC)DSA, Ed25519 does not rely on an entropy source when signing messages. This can be a potential attack vector if the entropy source is not generating good random numbers. Ed25519 avoids this problem entirely and will always generate the same signature for the same data.

So, I'm used to handling DSA signatures (historically -- this is what Sparkle and NetSparkleUpdater used to use), so I am used to seeing changing signatures. Ed25519 acts differently, and I didn't know it and never thought about seeing how ed25519 was different in that specific regard.

Thanks for helping me learn something today! ⭐️

**Comment by Deadpikle** [comment]
@johncclayton Huge kudos to you for all your help on this PR!! Many, many thanks for helping out. Your PR that fixed the unit tests -- thank you, and I added some more cleanup myself.

This is all merged in and rolling out to NuGet now.

**Comment by johncclayton** [comment]
I'm VERY glad to have been able to help!  Your work on creating the unit test structure to begin with eliminated one of my initial hurdles.   :-)

**Pull request merged**
